package API;

public class DescriptionAPI {

        // TODO REQUEST API URL AND API KEY TO Mediawiki

        // TODO GET API TO QUERY SUBJECT DESC AND GET BACK JSON FILE

        // TODO USE JSON FILE TO RETRIEVE SUBJECT DESC, SET DESC TEXT AREA TO DISPLAY SUBJECT DESC
}
